[package]
name = "xadreis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.14.0"
num_enum = "0.5.7"
unicode-segmentation = "1.10.0"
regex = "1.6.0"